### ISSUE TITLE
Schedule broken

### ISSUE THREAD

**Issue by jewellsean** [UBC-Stat-ML/stat520-sp2014-15-website#1]
Seems that the schedule is broken...missing `<br>` tags, I assume.

**Comment by sohrabsa** [comment]
Looks like it was introduced at 0a26ffba964a1282cfc9b38a14e09ff07d2ed6d4, in shift from comma separated to tab delimited. We'll look more into it.

**Comment by alexandrebouchard** [comment]
Thanks guys. Should be fixed now.
